obsidian_vault_path: /Users/colinluo/Library/Mobile Documents/iCloud~md~obsidian/Documents/obsidian-example-LifeOS-chinese-version/Info/X
headless_mode: false
max_tweets_limit: 100
sync_state:
  last_synced_id: '1997153810196648067'
  last_sync_time: '2025-12-06T16:44:05.352591'
